group: travis_latest
language: cpp
sudo: true

matrix:
  include:
    # Linux g++ build
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # Linux clang++ build
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    # OSX g++ build
    - os: osx
      compiler: gcc

    # OSX clang++ build
    - os: osx
      compiler: clang

before_install:
  - eval "${MATRIX_EVAL}"

install: true

script:
  - make && make test
